package net.swordie.ms.handlers.header;

import java.util.Arrays;
import java.util.List;

/**
 * Created on 2/18/2017.
 */
public enum OutHeader {

    // CLogin::OnPacket : v176 -> 00ADA117
    CHECK_PASSWORD_RESULT(0),
    ACCOUNT_INFO_RESULT(1),
    WORLD_INFORMATION(3),
    LATEST_CONNECTED_WORLD(23),
    RECOMMENDED_WORLD_MESSAGE(24),
    SET_CLIENT_KEY(),
    SET_PHYSICAL_WORLD_ID(),
    SELECT_WORLD_RESULT(4),
    SELECT_CHARACTER_RESULT(5),
    CREATE_MAPLE_ACCOUNT_RESULT(),
    CHECK_DUPLICATED_ID_RESULT(6),
    CREATE_NEW_CHARACTER_RESULT(7),
    DELETE_CHARACTER_RESULT(8),
    RESERVED_DELETE_CHARACTER_RESULT(9),
    RESERVED_DELETE_CHARACTER_CANCEL_RESULT(10),
    RENAME_CHARACTER_RESULT(15),
    SET_CHARACTER_ID(16),
    MIGRATE_COMMAND(13),
    ALIVE_REQ(14),
    PING_CHECK_RESULT(),
    AUTHEN_CODE_CHANGED(15),
    AUTHEN_MESSAGE(16),
    SECURITY_PACKET(22),
    PRIVATE_SERVER_PACKET(23),
    CHANGE_SPW_RESULT(24),
    MAPLOGIN(29),
    ALBA_RESULT(),
    SET_AUTO_SELECTED_WORLD(),
    WORLD_INFO_FOR_SHINING_RESULT(),
    SET_HOT_FIX(),
    SERVER_STATUS(),
    INIT_OPCODE_ENCRYPTION(),
    AUTH_SERVER(),

    // CChatSocket::ProcessPacket
    CHAT_LOGIN_RESULT(1),
    CHAT_LOGOUT_RESULT(11),
    CHAT_ALIVE_REQ(13),
    CHAT_ENTER_GUILD_CHAT_ROOM_RESULT(15),
    CHAT_GUILD_CHAT_MESSAGE(18),
    CHAT_FRIEND_CHAT_MESSAGE(19),
    CHAT_BLOCK_GUILD_FRIEND_CHAT(28),

    // CMapLoadable::OnPacket
    SET_BACK_EFFECT(),
    SET_MAP_TAGGED_OBJECT_VISISBLE(),
    SET_MAP_tAGGED_OBJECT_SMOOTH_VISIBLE(),
    SET_MAP_TAGGED_OBJECT_ANIMATION(),
    SET_MAP_OBJECT_ANIMATION(),
    SET_MAP_OBJECT_VISIBLE(),
    SET_MAP_OBJECT_MOVE(),
    SET_MAP_OBJECT_CREATE_LAYER(),
    SET_SPINE_BACK_EFFECT(),
    SET_SPINE_OBJECT_EFFECT(),
    CREATE_SPINE_RECT_EVENT(),
    REMOVE_SPINE_RECT_EVENT(),
    SPINE_RE_ADD_BACK_EVENT(),
    SPINE_RE_ADD_OBJECT_EVENT(),
    CREATE_CAMERA_CTRL_ZONE(),
    REMOVE_CAMERA_CTRL_ZONE(),
    UNK69(),
    RELOAD_BACK(),

    // CWvsContext::OnPacket
    INVENTORY_OPERATION(33),
    INVENTORY_GROW(34),
    STAT_CHANGED(35),
    TEMPORARY_STAT_SET(36),
    TEMPORARY_STAT_RESET(37),
    FORCED_STAT_SET(38),
    FORCED_STAT_RESET(39),
    CHANGE_SKILL_RECORD_RESULT(40),
    CHANGE_STEAL_MEMORY_RESULT(41),
    USER_DAMAGE_ON_FALLING_CHECK(),
    PERSONAL_SHOP_BUY_CHECK(),
    MOB_DROP_MESO_PICKUP(),
    BREAK_TIME_FIELD_ENTER(),
    RUNE_ACT_SUCCESS(43),
    RESULT_STEAL_SKILL_LIST(44),
    SKILL_USE_RESULT(45),
    EXCL_REQUEST(46),
    // 47
    GIVE_POPULARITY_RESULT(48),
    MESSAGE(49),
    MEMO_RESULT(50),
    MAP_TRANSFER_RESULT(51),
    ANTI_MACRO_RESULT(52),
    ANTI_MACRO_BOMB_RESULT(53),
    // 54
    CLAIM_RESULT(55),
    SET_CLAIM_SVR_AVAILABLE_TIME(56),
    CLAIM_SVR_STATUS_CHANGED(57),
    STAR_PLANET_USER_COUNT(),
    SET_TAMING_MOB_INFO(58),
    QUEST_CLEAR(59),
    ENTRUSTED_SHOP_CHECK_RESULT(60),
    SKILL_LEARN_ITEM_RESULT(61),
    SKILL_RESET_ITEM_RESULT(62),
    ABILITY_RESET_ITEM_RESULT(63),
    EXP_CONSUME_ITEM_RESULT(64),
    EXP_ITEM_GET_RESULT(65),
    CHAR_SLOT_INC_RESULT(66),
    // 67
    CHAR_RENAME_RESULT(68),
    // 69
    GATHER_ITEM_RESULT(70),
    SORT_ITEM_RESULT(71),
    // 72
    // 73
    CHARACTER_INFO(74),
    // 75
    PARTY_RESULT(76),
    PARTY_MEMBER_CANDIDATE_RESULT(77),
    URUS_PARTY_MEMBER_CANDIDATE_RESULT(),
    PARTY_CANDIDATE_RESULT(78),
    URUS_PARTY_RESULT(),
    INTRUSION_FRIEND_CANDIDATE_RESULT(79),
    INTRUSION_LOBBY_CANDIDATE_RESULT(80),
    // 81
    EXPEDITION_RESULT(82),
    FRIEND_RESULT(83),
    STAR_FRIEND_RESULT(),
    LOAD_ACCOUNT_ID_OF_CHARACTER_FRIEND_RESULT(),
    GUILD_REQUEST(84),
    GUILD_RESULT(85),
    ALLIANCE_RESULT(86),
    TOWN_PORTAL(87),
    BROADCAST_MSG(88),
    // 89
    INCUBATOR_RESULT(90),
    INCUBATOR_HOT_ITEM_RESULT(91),
    SHOP_SCANNER_RESULT(92),
    SHOP_LINK_RESULT(93),
    AUCTION_RESULT(94),
    AUCTION_MESSAGE(95),
    MARRIAGE_REQUEST(96),
    MARRIAGE_RESULT(97),
    WEDDING_GIFT_RESULT(98),
    NOTIFY_MARRIED_PARTNER_MAP_TRANSFER(99),
    CASHPET_FOOD_RESULT(100),
    CASHPET_PICK_UP_ON_OFF_RESULT(101),
    CASHPET_SKILL_SETTING_RESULT(102),
    CASH_LOOK_CHANGE_RESULT(103),
    CASHPET_DYEING_RESULT(104),
    SET_WEEK_EVENT_MESSAGE(105),
    SET_POTION_DISCOUNT_RATE(106),
    BRIDLE_MOB_CATCH_FAIL(107),
    IMITATED_NPC_RESULT(108),
    IMITATED_NPC_DATA(109),
    // 110
    LIMITED_NPC_DISABLE_INFO(111),
    MONSTER_BOOK_SET_CARD(),
    MONSTER_BOOK_SET_COVER(),
    HOUR_CHANGE(130),
    MINIMAP_ON_OFF(131),
    CONSULT_AUTH_KEY_UPDATE(132),
    CLASS_COMPETITION_AUTH_KEY_UPDATE(133),
    WEB_BOARD_AUTH_KEY_UPDATE(134),
    SESSION_VALUE(135),
    PARTY_VALUE(136),
    FIELD_SET_VARIABLE(137),
    FIELD_VALUE(138),
    BONUS_EXP_RATE_CHANGED(139),
    FAMILY_CHART_RESULT(140),
    FAMILY_INFO_RESULT(141),
    FAMILY_RESULT(142),
    FAMILY_JOIN_REQUEST(143),
    FAMILY_JOIN_REQUEST_RESULT(144),
    FAMILY_JOIN_ACCEPTED(145),
    FAMILY_PRIVILEGE_LIST(146),
    FAMILY_FAMOUS_POINT_INC_RESULT(147),
    FAMILY_NOTIFY_LOGIN_OR_LOGOUT(148),
    FAMILY_SET_PRIVILEGE(149),
    FAMILY_SUMMON_REQUEST(150),
    NOTIFY_LEVEL_UP(151),
    NOTIFY_WEDDING(152),
    NOTIFY_JOB_CHANGE(153),
    SET_BUY_EQUIP_EXT(154),
    SET_PASSENSER_REQUEST(155), // typo?
    // 156
    SCRIPT_PROGRESS_MESSAGE_BY_SOUL(157),
    SCRIPT_PROGRESS_MESSAGE(158),
    SCRUOT_PROGRESS_ITEM_MESSAGE(159),
    STATIC_SCREEN_MESSAGE(160),
    OFF_STATIC_SCREEN_MESSAGE(161),
    WEATHER_EFFECT_NOTICE(162),
    WEATHER_EFFECT_NOTICE_Y(),
    PROGRESS_MESSAGE_FONT(163),
    DATA_CRC_CHECK_FAILED(164),
    SHOW_SLOT_MESSAGE(),
    WILD_HUNTER_INFO(165),
    ZERO_INFO(166),
    ZERO_WP(167),
    ZERO_INFO_SUB_HP(168),
    // 169
    // 170
    UI_OPEN(171),
    CLEAR_ANNOUNCED_QUEST(172),
    RESULT_INSTANCE_TABLE(173),
    COOL_TIME_SET(174),
    ITEM_POT_CHANGE(175),
    SET_ITEM_COOL_TIME(176),
    SET_AD_DISPLAY_INFO(177),
    SET_AD_DISPLAY_STATUS(178),
    SET_SON_OF_LINKED_SKILL_RESULT(179),
    SET_MAPLE_STYLE_INFO(180),
    SET_BUY_LIMIT_COUNT(181),
    RESET_BUY_LIMIT_COUNT(182),
    UPDATE_UI_EVENT_LIST_INFO(183),
    DOJANG_RANKING_RESULT(184),
    // 185
    // 186
    SHUTDOWN_MESSAGE(187),
    RESULT_SET_STEAL_SKILL(188),
    SLASH_COMMAND(189),
    START_NAVIGATION(190),
    FUNCKEY_SET_BY_SCRIPT(191),
    CHARACTER_POTENTIAL_SET(192),
    CHARACTER_POTENTIAL_RESET(193),
    CHARACTER_HONOR_EXP(),
    //
    ASWAN_RESULT(),
    READY_FOR_RESPAWN(222),
    READY_FOR_RESPAWN_BY_POINT(223),
    OPEN_READY_FOR_RESPAWN_UI(224),
    CHARACTER_HONOR_GIFT(225),
    CROSS_HUNTER_COMPLETE_RESULT(226),
    CROSS_HUNTER_SHOP_RESULT(227),
    SET_CASH_ITEM_NOTICE(228),
    SET_SPECIAL_CASH_ITEM(229),
    SHOW_EVENT_NOTICE(230),
    BOARD_GAME_RESULT(231),
    YUT_GAME_RESULT(232),
    VALUE_PACK_RESULT(233),
    NAVI_FLYING_RESULT(234),
    SET_EXCL_REQUEST_SENT(235),
    CHECK_WEDDING_EX_RESULT(236),
    BINGO_RESULT(237),
    BINGO_CASSANDRA_RESULT(238),
    UPDATE_VIP_GRADE(239),
    MESO_RANGER_RESULT(240),
    SET_MAPLE_POINT(216),
    // 217
    SET_MIRACLE_TIME_INFO(218),
    HYPER_SKILL_RESET_RESULT(219),
    GET_SERVER_TIME(220),
    GET_CHARACTER_POSITION(221),
    // 222
    RETURN_EFFECT_CONFIRM(223),
    RETURN_EFFECT_MODIFIED(224),
    WHITE_ADDTIONAL_CUBE_RESULT(),
    BLACK_CUBE_RESULT(225),
    MEMORIAL_CUBE_RESULT(226),
    MEMORIAL_CUBE_MODIFIED(227),
    DRESS_UP_INFO_MODIFIED(228),
    RESET_STATE_FOR_OFF_SKILL(229),
    SET_OFF_STATE_FOR_OFF_SKILL(230),
    ISSUE_RELOGIN_COOKIE(231),
    AVATAR_PACK_TEST(232),
    // 233
    EVOLVING_RESULT(234),
    // 235
    ACTION_BAR_RESULT(236),
    GUILD_SEARCH_RESULT(237),
    HALLOWEEN_CANDY_RANKING_RESULT(238),
    GET_REWARD_RESULT(239),
    MENTORING(240),
    GET_LOTTERY_RESULT(241),
    CHECK_PROCESS_RESULT(242),
    COMPLETE_NPC_SPEECH_SUCCESS(243),
    COMPLETE_SPECIAL_CHECK_SUCCESS(243),
    SET_ACCOUNT_INFO(244),
    SET_GACHAPFEVER_TIME_INFO(245),
    AVATAR_MEGAPHONE_RES(246),
    SET_AVATAR_MEGAPHONE(247),
    CLEAR_AVATAR_MEGAPHONE(248),
    REQUEST_EVENT_LIST(249),
    LIKE_POINT(250),
    SIGN_ERROR_ACK(251),
    ASK_AFTER_ERROR_ACK(252),
    EVENT_NAME_TAG(253),
    ACQUIRE_EVENT_NAME_TAG(254),
    JOB_FREE_CHANGE_RESULT(255),
    EVENT_LOTTERY_OPEN(256),
    EVENT_LOTTERY_RESULT(257),
    // +8
    SCREEN_MSG(265),
    LIMIT_GOODS_NOTICE_RESULT(293),
    MONSTER_BATTLE_SYSTEM_RESULT(295),
    MONSTER_BATTLE_COMBAT_RESULT(296),
    UNIVERSE_BOSS_IMPOSSIBLE(298),
    CASH_SHOP_PREVIEW_INFO(299),
    CHANGE_SOUL_COLLECTION_RESULT(300),
    SELECT_SOUL_COLLECTION_RESULT(301),
    MASTER_PIECE_REWARD(302),
    PENDANT_SLOT_INC_RESULT(303),
    BOSS_ARENA_MATCH_SUCCESS(304),
    BOSS_ARENA_MATCH_FAIL(305),
    BOSS_ARENA_MATCH_REQUEST_DONE(306),
    USER_SOUL_MATCHING(307),
    CATAPULT_UPGRADE_SKILL(308),
    CATAPULT_RESET_SKILL(309),
    PARTY_QUEST_RANKING_RESULT(310),
    SET_COORDINATION_CONTEST_INFO(311),
    WORLD_TRANSFER_RESULT(312),
    TRUNK_SLOT_INC_RESULT(313),
    ELITE_MOB_WMI(314),
    RANDOM_PORTAL_NOTICE(),
    NOTIFY_WORLD_TRANSFER_HELPER(316),
    EQUIPMENT_ENCHANT(317),
    TOP_TOWER_RANK_RESULT(318),
    FRIEND_TOWER_RANK_RESULT(319),
    TOWER_RESULT_UI_OPEN(320),
    MANNEQUIN_RESULT(321),
    IRBOX_PACKET(322),
    CREATE_KOREAN_JUMPING_GAME(323),
    CREATE_SWING_GAME(324),
    UPDATE_MAPLE_TV_SHOW_TIME(325),
    RETURN_TO_TITLE(326),
    RETURN_TO_CHARACTER_SELECT(327),
    FLAME_WIZARD_FLAME_WALK_EFFECT(328),
    FLAME_WIZARD_FLARE_BLINK(329),
    SUMMONED_AVATAR_SYNC(330),
    CASH_SHOP_EVENT_INFO(331),
    BLACK_LIST(332),
    OPEN_UI_TEST(333),
    SWITCH_BLACK_LIST_VIEW(334),
    SCROLL_UPGRADE_FEVER_TIME(335),
    TEXT_EQUIP_INFO(336),
    TEXT_EQUIP_UI_OPEN(337),
    UI_STAR_PLANET_MINI_GAME_RESULT(),
    UI_STAR_PLANET_TREND_SHOP(),
    UI_STAR_PLANET_MINI_GAME_QUEUE(),
    STAR_PLANET_ROUND_INFO(),
    STAR_PLANET_RESULT(),
    BACK_SPEED_CTRL(344),
    SET_MAZE_AREA(345),
    CHARACTER_BURNING(),
    BATTLE_STAT_CORE_INFO(347),
    BATTLE_STAT_CORE_ACK(348),
    GACHAPTEST_RESULT(349),
    MASTER_PIECE_TEST_RESULT(350),
    ROYAL_STYLE_TEST_RESULT(351),
    BEAUTY_COUPTEST_RESULT(352),
    NICK_SKILL_EXPIRED(353),
    RANDOM_MISSION_RESULT(354),
    ON_12TH_TRESURE_RESULT(355),
    ON_12TH_TRESURE_BUFF(356),
    ITEM_COLLECTION_RESULT(357),
    CHECK_COLLECTION_COMPLETE_RESULT(358),
    ITEM_COLLECTION_LIST(359),
    RECEIVE_TOADS_HAMMER_REQUEST_RESULT(360),
    RECEIVE_HYPER_STAT_SKILL_RESET_RESULT(361),
    INVENTORY_OPERATION_RESULT(362),
    GET_SAVED_URUS_SKILL(363),
    SET_ROLE_PLAYING_CHARACTER_INFO(364),
    MVP_ALARM(365),
    MONSTER_COLLECTION_RESULT(366),
    TOWER_CHAIR_SETTING_RESULT(367),
    NEED_CLIENT_RESPONSE(368),
    CHARACTER_MODIFIED(369),
    TRADE_KING_SHOP_ITEM(370),
    TRADE_KING_SHOP_RES(371),
    PLATFORMAR_ENTER_RESULT(372),
    PLATFORMAR_OXYZEN(373),
    GUILD_BBS_RESULT(384),

    MACRO_SYS_DATA_INIT(335),

    // CStage::OnPacket : v176 -> 00E75B70
    SET_FIELD(336),
    SET_FARM_FIELD(337),
    // sub_E759A0(430),
    SET_CASH_SHOP(338),

    // CMapLoadable::OnPacket 339~343

    // CField::OnPacket (general) : v176 -> 00844E10
    TRANSFER_FIELD_REQ_IGNORED(344),
    TRANSFER_CHANNEL_REQ_IGNORED(345),
    TRANSFER_PVP_REQ_IGNORED(346),
    FIELD_SPECIFIC_DATA(347),
    GROUP_MESSAGE(348),
    FIELD_UNIVERSE_MESSAGE(349),
    WHISPER(350),
    SUMMITEM_INAVAILABLE(351),
    FIELD_EFFECT(352),
    // 353 str+int
    // 354
    // 355
    BLOW_WEATHER(356),
    PLAY_JUKE_BOX(357),
    ADMIN_RESULT(358),
    QUIZ(359),
    FIELD_SET_DESC(360),
    CLOCK(361),
    SET_QUEST_CLEAR(362),
    SET_QUEST_TIME(363),
    SET_OBJECT_STATE(364),
    DESTROY(365),
    // 366
    STALK_RESULT(367),
    // CField_Massacre::OnPacket
    MASSACRE_INC_GAUGE(368),
    MASSACRE_RESULT(369),
    // CField::OnPacket
    INIT(370),
    // 371
    // 372
    FOOT_HOLD_MOVE(373),
    CORRECT_FOOT_HOLD_MOVE(374),
    FOOT_HOLD_APPEAR(375),
    SMART_MOB_NOTICE(376),
    CHANGE_PHASE(377),
    CHANGE_MOB_ZONE(378),
    // 379
    PVP_MIGRATE_INFO_RESULT(380),
    CUR_NODE_EVENT_END(381),
    CREATE_FORCE_ATOM(382),
    SET_ACHIEVE_RATE(383),
    SET_QUICK_MOVE_INFO(384),
    CHANGE_ASWAN_SIEGE_WEAPGAUGE(385),
    CREATE_OBTACLE(386),
    CLEAR_OBTACLE(387),
    B2_FOOT_HOLD_CREATE(388),
    DEBUFF_OBJ_ON(389),
    // 390
    // 391
    CREATE_FALLING_CATCHER(392),
    CHASE_EFFECT_SET(393),
    MESO_EXCHANGE_RESULT(394),
    SET_MIRROR_DUNGEINFO(395),
    SET_INTRUSION(396),
    CANNOT_DROP(397),
    FOOT_HOLD_OFF(398),
    LADDER_ROPE_OFF(399),
    MOMENT_AREA_OFF(),
    MOMENT_AREA_OFF_ALL(),
    CHAT_LET_CLIENT_CONNECT(400),
    CHAT_INDUCE_CLIENT_CONNECT(401),
    PACKET(402),
    ELITE_STATE(403),
    PLAY_SOUND(404),
    STACK_EVENT_GAUGE(),
    SET_UNION_FIELD(),
    STAR_PLANET_BURNING_TIME_INFO(),
    PUBLIC_SHARE_STATE(),
    FUNCTION_TEMP_BLOCK(),
    UI_STATUS_BAR_PACKET(),
    FIELD_SKILL_DELAY(),
    WEATHER_PACKET_ADD(),
    WEATHER_PACKET_REMOVE(),
    WEATHER_PACKET_MSG(),
    ADD_WRECKAGE(),
    DEL_WRECKAGE(),
    CREATE_MIRROR_IMAGE(),
    FUNTION_FOOTHOLD_MAN(),

    // CField_KillCount::OnPacket
    FIELD_KILL_COUNT(470),

    // CUserPool::OnPacket?
    USER_ENTER_FIELD(407),
    USER_LEAVE_FIELD(408),

    // CUserPool::OnCommonPacket : v176 -> 018566C0
    CHAT(409),
    CHAT2(410),
    // 411
    AD_BOARD(412),
    MINI_ROOM_BALLOON(413),
    SET_CONSUME_ITEM_EFFECT(414),
    SHOW_ITEM_UPGRADE_EFFECT(415),
    // 416
    SHOW_ITEM_SKILL_SOCKET_UPGRADE_EFFECT(417),
    SHOW_ITEM_SKILL_OPTION_UPGRADE_EFFECT(418),
    SHOW_ITEM_RELEASE_EFFECT(419),
    SHOW_ITEM_UNRELEASE_EFFECT(420),
    SHOW_ITEM_LUCKY_ITEM_EFFECT(421),
    SHOW_ITEM_MEMORIAL_EFFECT(422),
    SHOW_ITEM_ADDITIONAL_UN_RELEASE_EFFECT(423),
    SHOW_ITEM_ADDITIONAL_SLOT_EXTEND_EFFECT(427),
    SHOW_ITEM_FIRE_WORKS_EFFEC(),
    SHOW_ITEM_OPTION_CHANGE_EFFECT(),
    RED_CUBE_RESULT(),
    HIT_BY_USER(432), // OnHitByUser -> KMST, verified v176 idb
    DOT_BY_USER(433), // OnDotByUser
    RESET_ALL_DOT(434), // OnResetAllDot
    DAMAGE_BY_USER(435), // OnDamageByUser
    TESLA_TRIANGLE(436),
    FOLLOW_CHARACTER(437),
    SHOW_PQ_REWARD(438),
    SET_ONE_TIME_ACTION(542),
    MAKING_SKILL_RESULT(543),
    SET_MAKING_MEISTER_SKILL_EFF(544),
    GATHER_RESULT(545),
    USER_EXPLODE(546),
    USER_HIT_BY_COUNTER(547),
    PYRAMID_LETHAL_ATTACK(548),
    MIXER_RESULT(549),
    WAIT_QUEUE_RESPONSE(550),
    CATEGORY_EVENT_NAME_TAG(551),
    SET_DAMAGE_SKIN(552),
    SET_PREMIUM_DAMAGE_SKIN(553),
    SET_SOUL_EFFECT(554),
    SIT_RESULT(555),
    STAR_PLANET_POINT_INFO(),
    STAR_PLANET_AVATAR_LOOK_SET(),
    TOSSED_BY_MOB_SKILL(558),
    BATTLE_ATTACK_HIT(559),
    BATTLE_USER_HIT_BY_MOB(560),
    FREEZE_HOT_EVENT_INFO(561),
    EVENT_BEST_FRIEND_INFO(562),
    SET_REPEAT_ONE_TIME_ACTION(563),
    SET_REPLACE_MOVE_ACTION(564),
    IN_GAME_CUBE_RESULT(565),
    SET_ACTIVE_EMOTICON_ITEM(567),
    CREATE_PSYCHIC_LOCK(568),
    RECREATE_PATHPSYCHIC_LOCK(569),
    RELEASE_PSYCHIC_LOCK(570),
    RELEASE_PSYCHIC_LOCK_MOB(571),
    CREATE_PSYCHIC_AREA(572),
    RELEASE_PSYCHIC_AREA(573),
    RW_ZERO_BUNKER_MOB_BIND(574),
    BEAST_FORM_WING_OFF(575),
    SET_MESO_CHAIR_COUNT(576),
    REFRESH_NAME_TAG_MARK(577),
    STIGMA_EFFECT(578),
    //    SHOW_POTENTIAL_BLACK_CUBE(529),
    GACHAPON_EFFECT(616),

    // CUser::OnPetPacket
    PET_ACTIVATED(579),
    PET_MOVE(580),
    PET_ACTION(581),
    PET_ACTION_SPEAK(582),
    PET_NAME_CHANGED(583),
    PET_LOAD_EXCEPTION_LIST(584),
    PET_HUE_CHANGED(585),
    PET_MODIFIED(586),
    PET_ACTION_COMMAND(589),

    // CUser::OnDragonPacket
    DRAGON_CREATED(590),
    DRAGON_MOVE(591),
    DRAGON_REMOVE(592),
    DRAGON_REMOVE_RP_CHAR(593),

    // CUser::OnAndroidPacket
    ANDROID_CREATED(594),
    ANDROID_MOVE(595),
    ANDROID_ACTION_SET(596),
    ANDROID_MODIFIED(),
    ANDROID_REMOVED(598),

    // CUser::OnFoxManPacket
    FOX_MAN_ENTER_FIELD(599),
    FOX_MAN_MOVE(600),
    FOX_MAN_EXCL_RESULT(601),
    FOX_MAN_SHOW_CHANGE_EFFECT(602),
    FOX_MAN_MODIFIED(603),
    FOX_MAN_LEAVE_FIELD(604),

    // CUser::OnSkillPetPacket
    SKILL_PET_MOVE(606),
    SKILL_PET_ACTION(607),
    SKILL_PET_STATE(608),

    // CFamiliar::OnPacket
    FAMILIAR_ENTER_FIELD(622),
    FAMILIAR_MOVE(623),
    FAMILIAR_HIT(624),
    FAMILIAR_ATTACK(625),
    FAMILIAR_RENAME(626),
    FAMILIAR_TRANSFER_FIELD(627),
    FAMILIAR_UPDATE_INFO(628),

    // CUserRemote::OnPacket : v176 -> 018548E0
    REMOTE_MOVE(506),
    // 507 null
    REMOTE_MELEE_ATTACK(508),
    REMOTE_SHOOT_ATTACK(509),
    REMOTE_MAGIC_ATTACK(510),
    REMOTE_BODY(511),
    REMOTE_SKILL_PREPARE(512),
    REMOTE_MOVING_SHOOT_ATTACK_PREPARE(513),
    REMOTE_SKILL_CANCEL(514),
    REMOTE_HIT(515),
    REMOTE_EMOTION(516),
    REMOTE_ANDROID_EMOTION(517),
    REMOTE_SET_ACTIVE_EFFECT_ITEM(518),
    REMOTE_SET_MONKEY_EFFECT_ITEM(519),
    REMOTE_SET_ACTIVE_NICK_ITEM(520),
    REMOTE_SET_DEFAULT_WING_ITEM(521),
    REMOTE_SET_KAISER_TRANSFORM_ITEM(522),
    REMOTE_SET_CUSTOM_RIDING(523),
    REMOTE_SHOW_UPGRADE_TOMB_EFFECT(524),
    REMOTE_SET_ACTIVE_PORTABLE_CHAIR(525), // 651=神之子學習成果
    REMOTE_AVATAR_MODIFIED(526),
    // 527
    // 528
    REMOTE_SET_TEMPORARY_STAT(529),
    REMOTE_RESET_TEMPORARY_STAT(530),
    REMOTE_RECEIVE_HP(531),
    REMOTE_GUILD_NAME_CHANGED(532),
    REMOTE_GUILD_MARK_CHANGED(533),
    REMOTE_PVP_TEAM_CHANGED(534),
    // 535
    REMOTE_UPDATE_PVP_HP_TAG(536),
    REMOTE_DRAGON_GLIDE(537),
    REMOTE_KEY_DOWN_AREA_MOVE_PATH(538),
    REMOTE_LASER_INFO_FOR_REMOTE(539),
    REMOTE_KAISER_COLOR_OR_MORPH_CHANGE(540),
    REMOTE_INTRUSION(541),
    REMOTE_ZERO_LAST_ASSIST_STATE(542),
    REMOTE_SCOUTER_MAX_DAMAGE_UPDATE(543),
    REMOTE_STIGMA_DELIVERY_RESPONSE(),
    REMOTE_EFFECT(551),
    REMOTE_GATHER_ACTION_SET(),
    REMOTE_DESTROY_GRENADE(),
    REMOTE_SET_ITEM_ACTION(),
    REMOTE_ZERO_TAG(),
    REMOTE_SET_MOVE_GRENADE(),
    REMOTE_SET_CUSTOMIZE_EFFECT(),
    REMOTE_RUNE_STONE_ACTION(),
    REMOTE_KINESIS_PSYCHIC_ENERGY_SHIELD_EFFECT(),
    REMOTE_DRAGON_ACTION(),
    REMOTE_DRAGON_BREATH_EARTH_EFFECT(),
    REMOTE_RELEASE_RW_GRAB(),
    REMOTE_RW_MULTI_CHARGE_CANCEL_REQUEST(),
    REMOTE_THROW_GRENADE(555),

    // CUserLocal::OnPacket
    EMOTION(556),
    ANDROID_EMOTION(557),
    EFFECT(558),
    // 559
    TELEPORT(560),
    // 561
    MESO_GIVE_SUCCEEDED(566),
    MESO_GIVE_FAILED(567),
    QUEST_RESULT(568),
    NOTIFY_HP_DEC_BY_FIELD(569),
    USER_PET_SKILL_CHANGED(570),
    BALLOON_MSG(571),
    PLAY_EVENT_SOUND(572),
    PLAY_MINIGAME_SOUND(573),
    MAKER_RESULT(574),
    OPEN_CLASS_COMPETION_TIPAGE(575),
    OPEN_UI(576),
    CLOSE_UI(577),
    OPEN_UI_WITH_OPTION(578),
    OPEN_WEB_UI(579),
    SET_DIRECTION_MODE(580),
    SET_IN_GAME_DIRECTION_MODE(581),
    SET_STAND_ALONE_MODE(582),
    HIRE_TUTOR(583),
    TUTOR_MSG(584),
    HIRE_TUTOR_BY_ID(585),
    SET_PARTNER(586),
    SET_PARTNER_ACTION(587),
    SET_PARTNER_FORCE_FLIP(588),
    SWITCH_RP(589),
    FP_PAY(590),
    FP_PAY_FAIL(591),
    MOD_COMBO_RESPONSE(592),
    INC_COMBO_RESPONSE_BY_COMBO_RECHARGE(593),
    RADIO_SCHEDULE(594),
    OPEN_SKILL_GUIDE(595),
    NOTICE_MSG(596),
    CHAT_MSG(597),
    SET_UTIL_DLG(598),
    BUFFZONE_EFFECT(599),
    TIME_BOMB_ATTACK(600),
    EXPLOSION_ATTACK(601),
    PASSIVE_MOVE(602),
    FOLLOW_CHARACTER_FAILED(603),
    SET_NEXT_SHOOT_EX_JABLIN(604),
    RESULT(605),
    GATHER_REQUEST_RESULT(606),
    RUNE_STONE_USE_ACK(607),
    BAG_ITEM_USE_RESULT(608),
    RANDOM_TELEPORT_KEY(609),
    SET_GAGE_POINT(610),
    IN_GAME_DIRECTION_EVENT(611),
    MEDAL_REISSUE_RESULT(612),
    DODGE_SKILL_READY(613),
    REMOVE_MICRO_BUFF_SKILL(614),
    VIDEO_BY_SCRIPT(615),
    REWARD_MOB_LIST_RESULT(616),
    INC_JUDGEMENT_STACK_RESPONSE(617),
    INC_CHARM_BY_CASHP_R_MSG(618),
    SET_BUFF_PROTECTOR(619),
    INC_LARKNESS_RESPONSE(620),
    DETONATE_BOMB(621),
    AGGRO_RANK_INFO_NAME(622),
    DEATH_COUNT_INFO(623),
    DEATH_COUNT_INFO_2(624),
    SET_DRESS_CHANGED(625),
    SERVER_ACK_MOB_ZONE_STATE_CHANGE(626),
    // 627
    // 628
    RANDOM_EMOTION(629),
    SET_FLIP_THE_COIN_ENABLED(630),
    TRICK_OR_TREAT_RESULT(631),
    GIANT_PET_BUFF(632),
    B2_BODY_RESULT(633),
    SET_DEAD(634),
    OPEN_UI_DEAD(),
    EXPIRED_NOTICE(),
    DO_LOTTERY_UI(),
    ROULETTE_START(),
    SIT_TIME_CAPSULE(),
    SIT_DUMMY_PORTABLE_CHAIR(),
    GO_MONSTER_FARM(),
    MONSTER_LIFE_INVITE_ITEM_RESULT(),
    PHOTO_GET_RESULT(),
    FINAL_ATTACK_REQUEST(639),
    SET_GUN(640),
    SET_AMMO(641),
    CREATE_GUN(642),
    CLEAR_GUN(643),
    RESULT_SHOOT_ATTACK_IN_FPS_MODE(644),
    MIRROR_DUNGEENTER_FAIL(645),
    MIRROR_DUNGEUNIT_CLEARED(646),
    REGISTER_MIRROR_DUNGEBOSS(647),
    MIRROR_DUNGERECORD(648),
    OPEN_URL(649),
    ZERO_COMBAT_RECOVERY(650),
    MIRROR_STUDY_UI_OPEN(651),
    SKILL_COOLTIME_REDUCE(652),
    MIRROR_READING_UI_OPEN(653),
    USER_CTRL_MOB_SKILL_Q_PUSH(654),
    ZERO_LEVEL_UP_ALARM(655),
    USER_CTRL_MOB_SKILL_Q_POP(656),
    USER_CTRL_MOB_SKILL_FAIL(657),
    FORCE_SUMMONED_REMOVE(658),
    USER_RESPAWN(659),
    USER_CTRL_MOB_SKILL_FORCED_POP(660),
    MONSTER_BATTLE_CAPTURE(661),
    IS_UNIVERSE(662),
    PORTAL_GROUP(663),
    SET_MOVABLE(792),
    USER_CTRL_MOB_SKILL_PUSH_COOL_TIME(793),
    MOVE_PARTICLE_EFF(794),
    DO_ACTIVE_EVENT_SKILL_BY_SCRIPT(795),
    SET_STATUSBAR_JOB_NAME_BLUR(796),
    RUNE_STONE_SKILL_ACK(),
    RESET_RUNE_STONE_ACTION(),
    MOVE_TO_CONTENTS_CANNOT_MIGRATE(),
    PLAY_AMBIENT_SOUND(),
    STOP_AMBIENT_SOUND(),
    FLAME_WIZARD_ELEMENT_FLAME_SUMMON(802),
    CAMERA_MODE(803),
    SPOTLIGHT_TO_CHARACTER(804),
    BOSS_PARTY_CHECK_DONE(805),
    FREE_LOOK_CHANGE_UI_OPEN(806),
    FREE_LOOK_CHANGE_SUCCESS(807),
    GRAY_BACKGROUND(808),
    GET_NPC_CURRENT_ACTION(809),
    CAMERA_ROTATION(810),
    CAMERA_SWITCH(811),
    NETWORK(812),
    USER_SET_FIELD_FLOATING(813),
    ADD_POPUP_SAY(814),
    REMOVE_POPUP_SAY(815),
    JAGUAR_SKILL(),
    ACTION_LAYER_RELMOVE(),
    SEND_CLIENT_RESOLUTION(),
    USER_BONUS_ATTACK_REQUEST(),
    USER_RAND_AREA_ATTACK_REQUEST(),
    JAGUAR_ACTIVE(),
    SKILL_COOLTIME_SET_M(822),
    SET_CARRY_REACTOR_INFO(823),
    REACTOR_SKILL_USE_REQUEST(824),
    OPEN_BATTLE_PV_PCHAMP_SELECT_UI(825),
    BATTLE_PVP_ITEM_DROP_SOUND(826),
    SET_MESO_COUNT_BY_SCRIPT(827),
    PLANT_POT_CLICK_RESULT(828),
    PLANT_POT_EFFECT(829),
    DAMAGE(830),
    ROYAL_GUARD_ATTACK(831),
    DO_ACTIVE_PSYCHIC_AREA(832),
    ENTER_FIELD_PSYCHIC_INFO(833),
    LEAVE_FIELD_PSYCHIC_INFO(834),
    TOUCH_ME_STATE_RESULT(835),
    FIELD_SCORE_UPDATE(836),
    URUS_REUSLT_UI_OPEN(),
    SET_NO_MORE_LIFE(838),
    SOME_DECODE4(839),
    CREATE_AREA_DOT_INFO(840),
    SET_SLOW_DOWN(841),
    REGISTER_EXTRA_SKILL(842),
    RES_WARRIOR_LIFT_MOB_INFO(843),
    USER_RENAME_RESULT(844),
    DAMAGE_SKIN_SAVE_RESULT(845),
    STIGMA_REMAIN_TIME(),
    OPEN_MESO_SACK_SUCCESS(847),
    OPEN_MESO_SACK_FAIL(848),

    FAMILIAR_ADD_RESULT(862),
    FAMILIAR_INVALID_NAME(863),

    MOD_HAYATO_COMBO(),
    ATK_TITAN_COIN_COUNT(710),
    SKILL_COOLTIME_SET(711),
    // 712

    // CSummonedPool::OnPacket
    SUMMONED_CREATED(713),
    SUMMONED_REMOVED(714),
    SUMMONED_MOVE(715),
    SUMMONED_ATTACK(716),
    SUMMONED_ATTACK_PVP(717),
    SUMMONED_SET_REFERENCE(718),
    SUMMONED_SKILL(719),
    SUMMONED_SKILL_PVP(720),
    SUMMONED_UPDATE_HP_TAG(721),
    SUMMONED_ATTACK_DONE(722),
    SUMMONED_SET_RESIST(),
    SUMMONED_ACTION_CHANGE(),
    SUMMONED_ASSIST_ATTACK_REQUEST(),
    SUMMONED_SUMMON_ATTACK_ACTIVE(723),
    SUMMONED_BEHOLDER_REVENGE_ATTACK(),
    SUMMONED_HIT(724),

    // CMobPool::OnPacket
    MOB_ENTER_FIELD(725),
    MOB_LEAVE_FIELD(726),
    MOB_CHANGE_CONTROLLER(727),
    MOB_SET_AFTER_ATTACK(728),
    MOB_BLOCK_ATTACK(),

    MOB_CRC_KEY_CHANGED(739),

    // CMobPool::OnMobPacket
    MOB_MOVE(729),
    MOB_CONTROL_ACK(730),
    // 731
    MOB_STAT_SET(732),
    MOB_STAT_RESET(733),
    MOB_SUSPEND_RESET(734),
    MOB_AFFECTED(735),
    MOB_DAMAGED(736),
    MOB_SPECIAL_EFFECT_BY_SKILL(737),
    MOB_CRC_DATA_REQUEST(738),
    // 739 在上面
    MOB_HP_INDICATOR(740),
    MOB_CATCH_EFFECT(741),
    MOB_STEAL_EFFECT(742),
    MOB_EFFECT_BY_ITEM(743),
    MOB_SPEAKING(744),
    MOB_MESSAGING(745),
    MOB_SKILL_DELAY(746),
    ESCORT_FULL_PATH(747),
    ESCORT_STOP_END_PERMISSION(748),
    ESCORT_STOP_BY_SCRIPT(749),
    ESCORT_STOP_SAY(750),
    ESCORT_RETURN_BEFORE(751),
    MOB_NEXT_ATTACK(752),
    MOB_TELEPORT_REQUEST(753),
    MOB_FORCED_ACTION(754),
    MOB_FORCED_SKILL_ACTION(755),
    MOB_TIME_RESIST(756),
    MOB_ONEKILL_DAMAGE(),
    MOB_ATTACK_BLOCK(757),
    MOB_ATTACK_PRIORITY(758),
    MOB_ATTACK_TIME_INFO(759),
    MOB_DAMAGE_SHARE_INFO_TO_LOCAL(760),
    MOB_DAMAGE_SHARE_INFO_TO_REMOTE(761),
    MOB_BREAK_DOWN_TIME_ZONE_TIME_OUT(762),
    MOB_MOVE_AREA_SET(763),
    MOB_DO_SKILL_BY_HIT(764),
    MOB_CASTING_BAR_SKILL(765),
    MOB_FLY_TARGET(766),
    MOB_BOUNCE_ATTACK_SKILL(767),
    MOB_AREA_INSTALL_BY_HIT(768),
    MOB_LTRB_DAMAGE_SKILL(769),
    MOB_SUMMSUB_BODY(958),
    MOB_LASER_CONTROL(959),
    MOB_SCALE(960),
    MOB_FORCE_CHASE(963),
    MOB_HANG_OVER_REQUEST(964),
    MOB_HANG_OVER_RELEASE_REQUEST(965),
    MOB_DEAD_FPS_MODE(966),
    MOB_AIR_HIT(967),
    MOB_DEMIAN_DELAYED_ATTACK_CREATE(),
    MOB_REGISTER_REL_MOB_ZONE(969),
    MOB_UNREGISTER_REL_MOB_ZONE(970),
    MOB_NEXT_TARGET_FROM_SVR(971),
    MOB_ATTACKED_BY_MOB(978),

    // +2

    // CMinionPool::OnPacket
    MINION_ENTER_FIELD(772),
    MINION_LEAVE_FIELD(773),
    MINION_CHANGE_CONTROLLER(774),
    MINION_GEN_BEYOND_SPLIT(775),

    // CNpcPool::OnPacket : v176 -> 00CB5250
    NPC_ENTER_FIELD(776),
    NPC_LEAVE_FIELD(777),
    NPC_ENTER_FIELD_FOR_QUICK_MOVE(778),
    NPC_CHANGE_CONTROLLER(779),

    NPC_IMITATE_DATA(122),
    NPC_UPDATE_LIMITED_DISABLE_INFO(124),
    SET_NPC_SCRIPT(793),

    // CNpcPool::OnNpcPacket : v176 -> 00CB4BF0
    NPC_MOVE(780),
    NPC_UPDATE_LIMITED_INFO(781),
    NPC_SET_QUIZ_SCORE(782),
    NPC_SET_QUIZ_SCORE_ANI(783),
    NPC_SET_FORCE_MOVE(784),
    NPC_SET_FORCE_FLIP(785),
    NPC_SET_EMOTION(786),
    NPC_SET_CHARACTER_BASE_ACTION(787),
    NPC_VIEW_OR_HIDE(788),
    NPC_PRESENT_ITEM_SET(),
    NPC_PRESENT_TIME_SET(),
    NPC_RESET_SPECIAL_ACTION(),
    NPC_SET_SCREEN_INFO(),
    NPC_LOCAL_NPC_REPEAT_EFFECT(),
    NPC_SET_NOTICE_BOARD_INFO(),
    NPC_SET_SPECIAL_ACTION(792),

    // CField_MomentSwimArea::OnPacket
    MOMENT_SWIM_AREA_SET_WATER_LEVEL(),

    // CEmployeePool::OnPacket
    EMPLOYEE_ENTER_FIELD(795),
    EMPLOYEE_LEAVE_FIELD(796),
    EMPLOYEE_MINI_ROOM_BALLOON(797),
    // 798

    // CDropPool::OnPacket
    DROP_ENTER_FIELD(799),
    // 800
    DROP_LEAVE_FIELD(801),

    // CMessageBoxPool::OnPacket
    CREATE_MESSAGE_BOX_FAILED(802),
    MESSAGE_BOX_ENTER_FIELD(803),
    MESSAGE_BOX_LEAVE_FIELD(804),

    // CAffectedAreaPool::OnPacket
    AFFECTED_AREA_CREATED(805),
    INSTALLED_AREA_FIRE(806),
    AFFECTED_AREA_REMOVED(807),

    // CTownPortalPool::OnPacket
    TOWN_PORTAL_CREATED(808),
    TOWN_PORTAL_REMOVED(809),

    // CRandomPortalPool::OnPacket
    RANDOM_PORTAL_CREATED(),
    RANDOM_PORTAL_TRY_ENTER_REQUEST(),
    RANDOM_PORTAL_REMOVED(),

    // COpenGatePool::OnPacket
    OPEN_GATE_CREATED(810),
    OPEN_GATE_CLOSE(),
    OPEN_GATE_REMOVED(811),

    // 812
    // 813
    // 814

    // CReactorPool::OnPacket
    REACTOR_CHANGE_STATE(815),
    REACTOR_IDK(816),
    REACTOR_ENTER_FIELD(817),
    REACTOR_RESET_STATE(818),
    REACTOR_OWNER_INFO(),
    REACTOR_REMOVE(),
    REACTOR_LEAVE_FIELD(819),

    // CFishingZonePool::OnPacket
    FISHING_INFO(),
    FISHING_REWARD(),
    FISHING_ZONE_INFO(),

    DECOMPOSER_ENTER_FIELD(),
    DECOMPOSER_LEAVE_FIELD(),

    // CField_GuildBoss::OnPacket
    GUILD_BOSS_HEALER_MOVE(1044),
    GUILD_BOSS_PULLEY_STATE_CHANGE(1045),

    // These are kinda scattered around
    MONSTER_CARNIVAL_CARNIVAL_ENTER(1046), // not a typo
    MONSTER_CARNIVAL_PERSONAL_CP(1047),
    MONSTER_CARNIVAL_TEAM_CSCORE(1048),
    MONSTER_CARNIVAL_SPELL_COOLTIME(1049),
    MONSTER_CARNIVAL_RESULT_SUCCESS(1050),
    MONSTER_CARNIVAL_RESULT_FAIL(1051),
    MONSTER_CARNIVAL_DEATH(1052),
    MONSTER_CARNIVAL_MEMBER_OUT(1053),
    MONSTER_CARNIVAL_SHOW_GAME_RESULT(1054),
    MONSTER_CARNIVAL_UPDATE_RANK_INFO(1055),

    // CField_AriantArena::OnPacket
    ARIANT_ARENA_SHOW_RESULT(460),
    ARIANT_ARENA_USER_SCORE(1056),

    // CField_Defense::OnPacket
    DEFENSE_WAVE(),
    DEFENSE_LIFE(),
    DEFENSE_POINT(),
    DEFENSE_SCORE_RANK(),
    DEFENSE_RESULT(),

    // CField_MultiStage::OnPacket
    MULTI_STAGE_SET_STAGE(1094),
    MULTI_STAGE_SET_MONSTER_GAUGE(1095),

    // CField_Piranha::OnPacket
    PIRANHA_INIT(1116),
    PIRANHA_INFO(1117),

    // CField_BossArena::OnPacket
    BOSS_ARENA_FIELD_STATE_CHANGE(1132),
    BOSS_ARENA_CURRENT_TEAM_INFO(1133),
    BOSS_ARENA_SELECTED_TEAM_INFO(1134),
    BOSS_ARENA_SELECT_OPPONENT_SELECT_BOSS(1135),
    BOSS_ARENA_SELECT_OPPONENT_CONFIRM(1136),
    BOSS_ARENA_SCORE(1141),
    BOSS_ARENA_RESULT_INFO(1142),
    BOSS_ARENA_FADE_IN_OUT(1144),
    BOSS_ARENA_SUMMON_HEAD_GEAR(1145),
    BOSS_ARENA_BOSS_INFO(1146),
    BOSS_ARENA_USER_HP_CHANGED(1147),

    // CField_BonusReward::OnPacket
    BONUS_REWARD_BOARD_FAO(1159),

    // CField_12th_Tresure::OnPacket
    TWELFTH_THREASURE_UPDATE_GAME_INFO(),
    TWELFTH_THREASURE_FIELD_STATE_CHANGE(),

    // CField_Demian::OnPacket
    DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET(),
    DEMIAN_STIGMA_OBJECT_EFFECT(),
    DEMIAN_FLYING_SWORD_CREATE(),
    DEMIAN_FLYING_SWORD_MAKE_ENTER_REQUEST(),
    DEMIAN_FLYING_SWORD_MAKE_ENTER_INFO(),
    DEMIAN_FLYING_SWORD_NODE(),
    DEMIAN_FLYING_SWORD_TARGET(),
    DEMIAN_CORRUPTION_CHANGE(),

    // Kinda unplaced
    FIELD_ON_RANK_CREATE(1113),
    FIELD_RANK_SET_USERNAME(1114),
    FIELD_RANK_NOTIFY_DATA(1115),
    FIELD_FADE_OBJECT_INFO(1155),
    RUNE_STONE_CLEAR_AND_ALL_REGISTER(938),
    RUNE_STONE_DISAPPEAR(939),
    RUNE_STONE_APPEAR(940),
    STAR_PLANET_SCREEN_WORLD_EVENT(),
    FIELD_STATE_CREATE(1161),
    FIELD_STATE_REMOVE(1162),
    CHASER_MOVE(1163),
    COMPLETE_RUNE(),
    HORNTAIL_TIMER(1207),
    ZAKUM_TIMER(1211),
    ZAKUM_TIMER2(1280),
    TRUNK_DLG(1308),
    RPS_GAME_DLG(1311),
    GO_STOP_RPS_GAME_DLG(1312),
    STAR_PLANET_GO_STOP_RPS_DLG(),
    UI_MESSENGER(1314),
    MINI_ROOM_BASE_DLG(1315),
    SET_CASH_SHOP_INITIAL_ITEM(1316),
    TRY_MIGRATE_CASH_SHOP(1317),
    PARCEL_DLG(1339),

    // CField_HundredBingo::OnPacket
    BINGO_ENTER_GAME(1179),
    BINGO_HOST_NUMBER(1180),
    BINGO_HOST_NUMBER_READY(1181),
    BINGO_ADD_RANK(1182),
    BINGO_REMOVE_RANK(1183),
    BINGO_FINISH_RANK(1184),
    BINGO_CHECK_NUMBER_ACK(1185),
    BINGO_GAME_STATE(1186),

    //
    GIVE_SPECIAL_SKILL_BAR(), // Used for Skills in certain bosses, such as Demian

    // CScriptMan::OnPacket
    SCRIPT_MESSAGE(979),

    // CShopDlg::OnPacket
    SHOP_OPEN(980),
    SHOP_RESULT(981),

    // CGachDlg::OnPacket
    GACH_OPEN(982),
    GACH_RESULT(983),

    // Field_Coordy::OnPacket
    COORDINATION_RUNWAY_AVATAR(984),

    // CStoreBankDlg::OnPacket
    STORE_BANK_GET_ALL_RESULT(985),
    STORE_BANK_RESULT(986),

    // CAdminShopDlg::OnPacket
    ADMIN_SHOP_RESULT(987),
    ADMIN_SHOP_COMMODITY(988),

    // CField_GhostPark::OnPacket
    GHOST_PARK_RUNE_USE_ACK(),
    GHOST_PARK_RUNE_APPEAR(),
    GHOST_PARK_RUNE_DISAPPEAR(),
    GHOST_PARK_KILLED_MOB_BONUS_EXP_RATE_INFO(),
    GHOST_PARK_CURSE_LEVEL_EXP_RATE(),
    GHOST_PARK_HOMING_BULLET_CREATE(),

    // +9

    // CCashShop::Init : v176 -> 01A1B510
    // CCashShop::OnPacket 1026 ~ 1058
    CASH_SHOP(1026),
    // 1027
    CASH_SHOP_QUERY_CASH_RESULT(1028),
    CASH_SHOP_CASH_ITEM_RESULT(1029),
    CASH_SHOP_PURCHASE_EXP_CHANGED(1030),
    // 1031
    CASH_SHOP_CHAR_STAT_CHANGED(1032),
    // 1033
    CASH_SHOP_IDK1(1034),
    // 1035
    CASH_SHOP_MVP_ITEM_GIVE_RESULT(1349), // probably
    CASH_SHOP_CHARGE_MILEAGE_NOTICE(1350),
    //
    CASH_SHOP_IDK2(1352),
    CASH_SHOP_IDK3(1353),
    //
    CASH_SHOP_IDK4(1355),
    CASH_SHOP_IDK5(1356),
    CASH_SHOP_IDK6(1357),
    CASH_SHOP_IDK7(1358),
    CASH_SHOP_IDK8(1359),
    CASH_SHOP_IDK9(1360),
    //
    //
    CASH_SHOP_IDK10(1363),
    CASH_SHOP_IDK11(1364),
    CASH_SHOP_INFO(), // In CClientSocket::ProcessPacket
    CASH_SHOP_ACTION(1366), // In CClientSocket::ProcessPacket
    //
    CASH_SHOP_IDK12(1368),
    //
    CASH_SHOP_IDK13(1370),
    CASH_SHOP_IDK14(1371),
    CASH_SHOP_IDK15(1372),

    // CFuncKeyMappedMan::OnPacket
    FUNC_KEY_MAPPED_MAN_INIT(1080),
    PET_CONSUME_ITEM_INIT(1081),
    PET_CONSUME_MP_ITEM(1082),
    // 1083
    // 1084

    // CUIGoldHammer::OnPacket
    GOLD_HAMMER_ITEM_UPGRADE_RESULT(1445),

    // CUIEgoEquip::OnPacket
    GAUGE_COMPLETE(1448),
    CREATE_UPGRADE_ITEM_COST_INFO(1449),
    CHECK_UPGRADE_ITEM_RESULT(1450),
    ITEM_UPGRADE_EFFECT(1451),

    // CFieldAttackObjPool::OnPacket
    FIELD_ATTACK_CREATE(1460),
    FIELD_ATTACK_REMOVE_BY_KEY(1461),
    FIELD_ATTACK_REMOVE_LIST(1462),
    FIELD_ATTACK_REMOVE_ALL(1463),
    FIELD_ATTACK_SET_ATTACK(1465),
    FIELD_ATTACK_RESULT_BOARD(1466),
    FIELD_ATTACK_RESULT_GET_OFF(1467),
    FIELD_ATTACK_PUSH_ACT(1468),
    FIELD_ATTACK_INFO(1470),

    // CBattleRecordMan::OnPacket
    DOT_DAMAGE_INFO(1472),
    KILL_DAMAGE_INFO(1473),
    BATTLE_DAMAGE_INFO(1474),
    SERVER_ON_CALC_REQUEST_RESULT(1475),
    AGGRO_MONITORING_INFO(1476),
    SKILL_DAMAGE_LOG(1477),

    // CMonsterFarm::OnPacket : v176 -> 00C69BC6
    FARM_UPDATE_INVENTORY(1496),
    FARM_CONSOLE_MESSAGE(1497), // empty func in v176??
    FARM_OBJECT_INTERACT(1498),
    FARM_CONSUME_OBJECT(1499),
    FARM_DICTIONARY_RESULT(1500),
    FARM_UPDATE_BUY_OBJECT(1501),
    FARM_UPDATE_SELL_OBJECT(1502),
    FARM_COMBINE_RESULT(1503),
    FARM_MONSTER_SEARCH_RESULT(1504), // in KMST redirects to CUIFarmMatching::OnPacket
    FARM_VISIT_RESULT(1505),
    FARM_UPDATE_NEWS_FEED(1506),
    FARM_UPDATE_DICTIONARY(1507),
    FARM_AUTO_HARVEST_RESULT(1508),
    FARM_SOUL_RECHARGE_RESULT(1509),

    // CFarmUser::OnPacket : v176 -> 007FB400
    FARM_SET_USER(1512),
    FARM_SET_INVENTORY(1513),
    FARM_SET_QUEST_ALL(1514),
    FARM_QUEST_MESSAGE(1515),
    FARM_NOTICE_MESSAGE(1516),
    FARM_UPDATE_MONSTER_LIST(1517),
    FARM_UPDATE_DECO(1518),
    FARM_UPDATE_POINT(1519),
    FARM_UPDATE_CASH(1520),
    FARM_UPDATE_THEME(1521),
    FARM_UPDATE_MONSTER_SLOT(1522),
    FARM_UPDATE_MONSTER_LOCKER_SLOT(1523),
    FARM_UPDATE_EXP(1524),
    FARM_RESULT_CHECK_NAME(1525),
    FARM_RESULT_CHECK_NAME_BY_CONSUME(1526),
    FARM_RESULT_COMPLETE_QUEST(1527),
    FARM_RESULT_GET_USER_PHOTO(1528),
    FARM_RESULT_UPDATE_PHOTO(1529),
    FARM_RESULT_REFILL_DAILY_QUEST(1530),
    FARM_SEND_GIFT(1531),
    FARM_SET_FRIEND_LIST(1532),
    FARM_ONLINE_REFRESH(1533),
    FARM_RESULT_ADD_FRIEND(1534),
    FARM_RESULT_SEND_NOTICE(1535), // corrupted in my pdb :(
    FARM_RESULT_LOAD_MAIN_LOG(1536),
    FARM_RESULT_ADD_BLACKLIST(1537),
    FARM_RESULT_USER_INFO_UI(1538),
    FARM_SET_GUEST_OWNER_INFO(1539),
    FARM_WHISPER(1540),
    FARM_GROUP_MESSAGE(1541),
    FARM_BROADCAST_MSG(1542),
    FARM_NEW_LIST_RESULT(1543), // CFarmFriendRecommendMan::OnResultNewList
    FARM_SET_IN_GAME_INFO(1544),
    FARM_FORCED_SHOP_OPEN(1545),
    FARM_REQUEST_SET_IN_GAME_INFO(1546),
    // UNK 1547
    FARM_RESULT_IN_GAME_FRIEND_REQUEST(1548),
    FARM_IN_GAME_FRIEND_EVENT(1549),
    FARM_RESULT_WORLD_WHISPER(1550),
    FARM_TOTAL_INFO(1551), // CFarmStaticClientMan::OnTotalInfo

    // CField_Zakum::OnPacket : v176 -> 0092FB00
    FIELD_ZAKUM_DYNAMIC_OBJ_VISIBLE(468),
    FIELD_ZAKUM_SYNC_DYNAMIC_FOOTHOLD(469),

    // CField_Urus::OnPacket : v176 -> 0092E230
    FIELD_URUS_DYNAMIC_OBJ_MOVE(467),
    FIELD_URUS_DYNAMIC_OBJ_VISIBLE(468),
    FIELD_URUS_SYNC_DYNAMIC_FOOTHOLD(469),

    // CField_SummonEvent::OnPacket : v176 -> 0091D220
    FIELD_SUMMONEVENT_EVENT_RANK(750),
    FIELD_SUMMONEVENT_EVENT_REWARD(751),

    // CField_SnowBall::OnPacket : v176 -> 00909DB0
    // todo :: op 1038 - 1041

    // CField_Witchtower::OnPacket : v176 -> 0092F770
    FIELD_WITCHTOWER_SCORE_UPDATE(1060),

    // CField_PvP::OnPacket : v176 -> 008E2990

    // CField_BaseBallDrop::OnPacket : v176 -> 008E7320
    FIELD_BASEBALLDROP_ONPACKET(1080), // (*(this[-1].m_mPoint._Mysize + 208))(&this[-1].m_mPoint._Mysize, iPacket);

    FIELD_RANDOMDROP_ONPACKET(1080), // idk why this is the same as above -- (*(*this[-1].m_pBNSmall.gap0 + 204))(&this[-1].m_pBNSmall, iPacket);
    FIELD_RANDOMDROP_ONPACKET2(1083), // (*(*this[-1].m_pBNSmall.gap0 + 208))(&this[-1].m_pBNSmall, iPacket);

    // CField_FlyingKiteDrop::OnPacket : V176 -> 008F1620
    FIELD_FLYINGKITEDROP_UNK(1081), // (this[-1].m_mPoint._Myhead[8]._Myval.second)(&this[-1].m_mPoint._Myhead, iPacket);
    FIELD_FLYINGKITEDROP_UNK2(1082), // single decode4 with a few pointer operations, not in a function in kmst
    FIELD_FLYINGKITEDROP_POINT_EFFECT(1084),

    // CField_PvPHardCore::OnPacket : v176 -> 008E71D0
    // todo :: op 1085 - 1093

    // CField_RhythmGame::OnPacket : v176 -> 008FCFA0
    // todo :: op 1097 - 1108
    FIELD_RHYTHMGAME_USER_NAME(1112),

    // CField_RunningGame::OnPacket : v176 -> 008FD3E0
    FIELD_RUNNINGGAME_MOB_INFO(1111),

    // CField_MountainRiding::OnPacket : v176 -> 008EBA50
    // todo :: op 1109 - 1111... why does this clash with running game??

    // CField_SpaceMoonRabbit::OnPacket : v176 -> 00912440
    // todo :: op 1148 - 1154

    // CField_PoloFritoBountyHunting::OnPacket : v176 -> 008D2B60
    FIELD_POLOFRITO_BOUNTYHUNTING_UPDATE_STAGE_INFO_UI(1166),

    // CField_PoloFritoTownDefense::OnPacket : v176 -> 008D66D0
    FIELD_POLOFRITO_TOWNDEFENSE_UPDATE_WAVE_INFO_UI(1167), // maybe shorten these names.. theyre kinda long ._.
    FIELD_POLOFRITO_TOWNDEFENSE_UPDATE_LINE_INFO_UI(1168),

    // CField_TypingGame::OnPacket : v176 -> 0092D7E0
    // todo :: op 1187 - 1198

    // CField_SideScrollFlyShooting : v176 -> 009077D0
    // todo :: op 1226 - 1232

    // CField_StarPlanetRps::OnPacket : V176 -> 009174B0
    // todo :: op 1219 - 1225

    // CField_Soul::OnPacket : v176 -> 0090B2F0
    // todo :: op 1295 - 1303



    SOCKET_CREATE_RESULT(1481),
    GOLLUX_MINIMAP(1568),
    GOLLUX_PORTAL_OPEN(1569),
    ;

    private static final List<OutHeader> spam = Arrays.asList(
            ALIVE_REQ,
            PRIVATE_SERVER_PACKET,
            MOB_CONTROL_ACK,
            CHAT_MSG,
            MOB_HP_INDICATOR,
            STAT_CHANGED,
            MOB_CHANGE_CONTROLLER,
            MOB_MOVE,
            REMOTE_MOVE,
            REMOTE_EMOTION,
            EXCL_REQUEST,
            NPC_MOVE,
            DROP_LEAVE_FIELD,
            TEMPORARY_STAT_RESET,
            PET_MOVE,
            NPC_ENTER_FIELD,
            NPC_CHANGE_CONTROLLER,
            MOB_ENTER_FIELD,
            RESULT_INSTANCE_TABLE,
            CREATE_OBTACLE,
            DROP_ENTER_FIELD,
            MOB_LEAVE_FIELD,
            ANDROID_MOVE,
            MESSAGE
    );

    private final short value;

    OutHeader() {
        this.value = (short) 9999;
    }

    OutHeader(int value) {
        this.value = (short) value;
    }

    public short getValue() {
        return value;
    }

    public static OutHeader getOutHeaderByOp(int op) {
        for (OutHeader outHeader : OutHeader.values()) {
            if (outHeader.getValue() == op) {
                return outHeader;
            }
        }
        return null;
    }

    public static boolean isSpamHeader(OutHeader outHeader) {
        return spam.contains(outHeader);
    }

}
