package net.swordie.ms.enums;

/**
 * Created on 1/25/2018.
 */
public enum MessageType {
    DROP_PICKUP_MESSAGE(0),
    QUEST_RECORD_MESSAGE(1),
    QUEST_RECORD_MESSAGE_ADD_VALID_CHECK(-1),
    CASH_ITEM_EXPIRE_MESSAGE(2),
    INC_EXP_MESSAGE(3),
    INC_SP_MESSAGE(4),
    INC_POP_MESSAGE(5),
    INC_MONEY_MESSAGE(6),
    INC_GP_MESSAGE(7),
    INC_COMMITMENT_MESSAGE(8),
    GIVE_BUFF_MESSAGE(9),
    GENERAL_ITEM_EXPIRE_MESSAGE(10),
    SYSTEM_MESSAGE(11),
    QUEST_RECORD_EX_MESSAGE(12),
    WORLD_SHARE_RECORD_MESSAGE(13),
    ITEM_PROTECT_EXPIRE_MESSAGE(14),
    ITEM_EXPIRE_REPLACE_MESSAGE(15),
    ITEM_ABILITY_TIME_LIMITED_EXPIRE_MESSAGE(16),
    SKILL_EXPIRE_MESSAGE(17),
    INC_NON_COMBAT_STAT_EXP_MESSAGE(18),
    LIMIT_NON_COMBAT_STAT_EXP_MESSAGE(19),
    // 20
    ANDROID_MACHINE_HEART_ALSET_MESSAGE(21),
    INC_FATIGUE_BY_REST_MESSAGE(22),
    INC_PVP_POINT_MESSAGE(23),
    PVP_ITEM_USE_MESSAGE(24),
    WEDDING_PORTAL_ERROR(25),
    INC_HARDCORE_EXP_MESSAGE(26),
    NOTICE_AUTO_LINE_CHANGED(27),
    ENTRY_RECORD_MESSAGE(28),
    EVOLVING_SYSTEM_MESSAGE(29),
    EVOLVING_SYSTEM_MESSAGE_WITH_NAME(30),
    CORE_INVEN_OPERATION_MESSAGE(31),
    NX_RECORD_MESSAGE(-1),
    BLOCKED_BEHAVIOR_MESSAGE(32),
    INC_WP_MESSAGE(33),
    MAX_WP_MESSAGE(34),
    STYLISH_KILL_MESSAGE(35),
    BARRIER_EFFECT_IGNORE_MESSAGE(-1),
    EXPIRED_CASH_ITEM_RESULT_MESSAGE(-1),
    COLLECTION_RECORD_MESSAGE(-1),
    RANDOM_CHANCE_MESSAGE(-1),
    UNK(220),

    ;

    private final byte val;

    MessageType(int val) {
        this.val = (byte) val;
    }

    public byte getVal() {
        return val;
    }
}
